# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "51a0ed6bbc55b7564582f1c1a0a922d7"
name = "under-it-all-report-cards"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]
